language: node_js

node_js:
  - "stable"

services:
 - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql_upgrade  
  - mysql -u root -e 'CREATE DATABASE zeus_node;'
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'haritha'@'localhost' IDENTIFIED WITH mysql_native_password BY 'haritha';"
  - mysql -u root -e "GRANT ALL ON zeus_spring.* TO 'haritha'@'localhost';"
  - cd noderest_controller
  
install:
  - npm i -g npm@5.7.1 
  - npm ci

script:
  - npm test
