language: node_js

node_js:
  - "stable"

services:
 - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql_upgrade  
  - mysql -u root -e 'CREATE DATABASE zeus_node;'
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'haritha'@'localhost' IDENTIFIED WITH mysql_native_password BY 'haritha';"
  - mysql -u root -e "GRANT ALL ON zeus_spring.* TO 'haritha'@'localhost';"
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('admin') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql_upgrade -u root -pnew_password
  - service mysql restart
  - cd noderest_controller
  
install:
  - npm install || cat npm-debug.log
  - npm install --save-dev mocha
  - npm install -g chai

script:
  - npm test
