language: java

jdk:
  - oraclejdk8
  
services:
  - mysql
  
dist: trusty

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:  
  - mysql -u root -e 'CREATE DATABASE zeus_spring;'
  - mysql -u root -e "CREATE USER 'aravind'@'localhost' IDENTIFIED BY 'aravind';"
  - mysql -u root -e "ALTER USER 'aravind'@'localhost' IDENTIFIED WITH mysql_native_password BY 'aravind';"
  - mysql -u root -e "GRANT ALL ON zeus_spring.* TO 'aravind'@'localhost';"
  
cache:
  directories:
    - $HOME/.m2

script:
  - cd Java_Spring_Ms && mvn clean install -DskipTests=false