apiVersion: v1
kind: Service
metadata:
  name: java-ms-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8090
    port: 8090
    nodePort: 30006
 selector:
  app: java-ms
 externalIPs:
  - 149.165.170.230
