
language: java

jdk:
  - oraclejdk8
  
services:
  - mysql
  
dist: trusty

sudo: required

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql_upgrade  

  - mysql -u root -e 'CREATE DATABASE zeus_node;'
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'haritha'@'localhost' IDENTIFIED WITH mysql_native_password BY 'haritha';"
  - mysql -u root -e "GRANT ALL ON zeus_node.* TO 'haritha'@'localhost';"
  
cache:
  directories:
    - $HOME/.m2

script:
  - cd Java_Spring_Ms && mvn clean install -DskipTests=false
