---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: java-ms 
   labels:
    app: web
spec:
   replicas: 3
   template:
    metadata:
     labels:
        app: web    
    spec:
       containers:
        - name: java-ms
          image: shayyag/java_ms 
          ports:
            - protocol: "TCP"
              containerPort: 92
          
            
---
kind: Service
apiVersion: v1
metadata:
  name: java-ms
  labels:
    app: web
spec:
  ports:
    - port: 8092
      name: java-ms
      protocol: "TCP"
      targetPort: 92
      nodePort: 30003
  type: LoadBalancer

  