---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: web
spec:
  replicas: 12
  template:
    metadata:
     labels:
        app: web    
    spec:
        containers:
             - name: mysql-deployment
               image: mysql/mysql-server:latest
               imagePullPolicy: IfNotPresent
               env:
                  - name: MYSQL_USER
                    value: root
                  - name: MYSQL_PASSWORD
                    value: root
                  - name: MYSQL_ROOT_PASSWORD
                    value: root
                  - name: MYSQL_DB
                    value: zeus_flask
               ports:
                  - containerPort: 3306 
                    protocol: "TCP"   

---
apiVersion: v1
kind: Service
metadata:
   name: mysql-service
spec:
   ports:
      - port: 3306
        protocol: "TCP"
   selector:
     app: web   
   type: LoadBalancer    