---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: node-rest 
   labels:
    app: web
spec:
   replicas: 3
   template:
    metadata:
     labels:
        app: web    
    spec:
       containers:
        - name: node-rest
          image: shayyag/node_rest_ms
          ports:
            - protocol: "TCP"
              containerPort: 80
          
            
---
kind: Service
apiVersion: v1
metadata:
  name: node-rest
  labels:
    app: web
spec:
  ports:
    - port: 8080
      name: node-rest
      protocol: "TCP"
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer

  