---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: node-rest-deployment
   labels:
    app: web
spec:
   replicas: 3
   template:
    metadata:
     labels:
        app: web    
    spec:
       containers:
        - name: node-rest-deployment
          image: shayyag/node_rest_ms
          ports:
            - protocol: "TCP"
              containerPort: 80
          
            
---
kind: Service
apiVersion: v1
metadata:
  name: node-rest-service
spec:
  selector: 
    app: web
  ports: 
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer
  
  

  